tasks:
  - name: Set up Java and build project
    init: |
      sdk install java 17.0.12-amzn
      sdk use java 17.0.12-amzn
      java -version  # Verifique se o Java 17 foi ativado corretamente
      mvn install -DskipTests=false